from strategies import utils
from .synaptic_intelligence import SynapticIntelligence
from .cope import COPE
from .dslda import DSLDA
from .ewc import EWC
from .agem import AGEM
from .gem import GEM
from .lwf import LwF
from .iCARL import iCARL
