from .synaptic_intelligence import SynapticIntelligence
from .cope import COPE
from .dslda import DSLDA
from .ewc import EWC
from .mas import MAS
from .agem import AGEM
from .gem import GEM
from .lwf import LwF
from .gss import GSS
from .mir import MIR
from .iCARL import iCARL
from .gdumb import GDumb
from .lfl import LFL
from .lamaml import LaMAML
from .generative_replay import GenerativeReplay
from .rwalk import RWalk
from .scr import SCR
from .er_ace import ER_ACE
from .er_aml import ER_AML
from .packnet import PackNet
from . import utils
